{% set name = "dramatiq" %}
{% set version = "1.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5d0036c37f2a6366b65b06581cb721cf14486511cac9c4250404885ef5bf454

build:
  noarch: python
  number: 0
  entry_points:
    - dramatiq = dramatiq.__main__:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - prometheus_client >=0.2
    - python >=3.6

test:
  imports:
    - dramatiq
    - dramatiq.brokers
    - dramatiq.middleware
    - dramatiq.rate_limits
    - dramatiq.rate_limits.backends
    - dramatiq.results
    - dramatiq.results.backends
  commands:
    - dramatiq --help

about:
  home: https://dramatiq.io
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING
  summary: Background Processing for Python 3.
  dev_url: https://github.com/Bogdanp/dramatiq

extra:
  recipe-maintainers:
    - lincrosenbach
    - nicoddemus
