{% set name = "dramatiq" %}
{% set version = "1.4.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a1db24f829be5c851f7a69a70122015b514c587a33700c82f73da2efb5298675

build:
  noarch: python
  number: 0
  entry_points:
    - dramatiq = dramatiq.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - prometheus_client >=0.2,<0.3
    - python >=3.5

test:
  imports:
    - dramatiq
    - dramatiq.brokers
    - dramatiq.middleware
    - dramatiq.rate_limits
    - dramatiq.rate_limits.backends
    - dramatiq.results
    - dramatiq.results.backends
  commands:
    - dramatiq --help

about:
  home: https://dramatiq.io
  license: GNU Lesser General Public v3 or later (LGPLv3+)
  license_family: LGPL
  license_file: COPYING 
  summary: Background Processing for Python 3.
  dev_url: https://github.com/Bogdanp/dramatiq

extra:
  recipe-maintainers:
    - lincrosenbach
    - nicoddemus  
