travis:
  secure:
    BINSTAR_TOKEN: JZQ+CPKpqE0KQjwAUjvPbg/NWJxA+Oc2DHTNKTxteWuYhYzwXq5sEbm6emYYIrr+CfTzSoqkBXy+x8SH33d+6scUnNtD1eL674uBxjgOIDThzY2bPk9EEhRmbmksDQ0qh5V0M/UE6dhmD1Zmi3x3KKAtBNj1U38Kh8vaRMQuypLi6pmcWWv3qkBSHxnp/FEatRyiqqLw2zk+zFN5hfcjQTblRsN04EJzDh/SFH8ytRUgCvWEvmnQtOilpuKAHm0v/C4rkdobMVQCv6yxhie2xgOuKD+dI9C0wVncnp4KCpj6b19t1TzAQMFKIU3PZj+IJ+TlijlFqG8V7UFG6IXiFNbl/xQHCPKKRi2HN9r2Y7F+t3Jwf6SCPfAn6GNPgDqwvuHhXfsAfe/tqBuDyKMuQkfsg2r0UyfYDRMtCi2UcFHoj+IWg13yc7RIlBnxh55rARHxWsIGYTTl+XLQVrDkekEi7QnNZRCNG6Afu/7qSZ/ZyLQxsKbX15dwhkq2rnOuut9tp+Lfv3N5RBgzhdp+QGgC+kxo6tFT13xqabJEFqbYLGoIf2jHSUxtZdoKu/6m2IuzlbnCGGMblDNu2G2ISdA/k0w6CO1N9fjhcSWkdXgFSREl/zwZzU4I3PJyh+XylGoKhVREUjevr3kzqxxzrBg4xjRrzF2FvCuD3JKYw/8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
